### PR TITLE
Fixes the package names

### PR DESCRIPTION
**Pull request by skyluc**
org.typesafe -> com.typesafe
mesostest -> com.typesafe.spark.mesos

### CODE REVIEW

**Comment by skyluc** [comment]
I will rebase on the other PRs when merged, but please review now.

**Comment by skonto** [comment]
I checked that all files are renamed. Do we need to provide any file headers when using com.typesafe? As an hierarchical convention another option would be com.typesafe.spark.test.mesos... 
This covers future needs i think as well (put everything relllevant under test umbrella). Other than that LGTM.

**Comment by skyluc** [comment]
I think `test.mesos` is a good idea.
We don't need headers, but we do need a LICENCE file in the root of the project.

**Comment by skyluc** [comment]
Rebased, and updated the package names to:

org.typesafe.spark.mesos -> com.typesafe.spark.test.mesos
mesostest -> com.typesafe.spark.test.mesos

**Comment by skonto** [comment]
should i merge it?

**Pull request merged**
