### PR TITLE
Adds latch to wait for the connection to zookeeper

### PR DESCRIPTION
**Pull request by skyluc**
The following commands fail if the connection is not established
before they are run.

### CODE REVIEW

**Comment by skonto** [comment]
I guess this is for EC2 or anything other than local tests, because in the latter if things have run normally there is a check in run.sh if the service is up already...

**Comment by skyluc** [comment]
Yes, I had the problem on ec2, but it is not a problem of the service not being up.

`new ZooKeeper(zkConnection, 3000, null)` is an asynchronous action, so it returns before the connection is fully established, and `ZKUtil.deleteRecursive(zk, path);` will fail with a `ConnectionLossException` if run before the connection is fully up.

So it just has to wait for the event about the connection being up.

**Comment by skonto** [comment]
ok im looking it...

**Comment by skonto** [comment]
The only problem i see is that if there is no connection/session it will block for ever... we should fail there after timeout. In order this to happen you could wrap the code with the callback in a future,
fulfill a promise in the callback and let the rest of the code wait on the future of the promise so we get a timeoutexception in case of no session occurs...

**Comment by skyluc** [comment]
I updated the latch with a timeout.

**Comment by skonto** [comment]
Even better with the timeout await. testing it.

**Comment by skonto** [comment]
As a side note when there is no zookeeper the other test suites fail with:
- simple collect in fine-grained mode *** FAILED ***
  Could not obtain a SparkContext in due time, check logs for Mesos errors (MesosIntTestHelper.scala:57)

.. just wanted to point this out for reference, there is no precondition check to fail fast as in this case where we actually access zk by its api.
LGTM!

**Pull request merged**
