### PR TITLE
fix for new build process

### LINKED ISSUE #73: Tests fail because of https://issues.apache.org/jira/browse/SPARK-13579
https://ci.typesafe.com/job/mit-docker-test-ref/106/
We need to change the path for the files and how dependencies are collected.

### PR DESCRIPTION
**Pull request by skonto**
fixes #73

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by dragos** [comment]
Let's wait for Travis and then merge.

**Comment by skonto** [comment]
fails because spark.home is not defined let me add a check..

**Comment by skonto** [comment]
Ok i think its working now.... check my fix if there is a constructor to use instead of the dummy let me know ... i thought i could just add a list of Attributes for the dummy part but does not work.

**Comment by dragos** [comment]
Yeah, I think it's fine. Let's merge this

**Pull request merged**
