### PR TITLE
dind

### LINKED ISSUE #77: Mesos needs docker to run in docker - use dind
The problem:

Mesos uses docker to run tasks. For the slaves when they start they need to check if the docker binary is available. In our suite we run slaves within docker. @mgummelt has previously proposed this path as well.

Facts:
a. Docker binary from version to version has different dependencies needed at runtime.
There are static versions of the binary which could be pre-installed but that does not solve the problem because there would be incompatibilities with the server on the host.

b. Docker is not compatible when server and client have different  versions:  https://github.com/docker/docker/issues/14077

c. So far the solution we have with image pre-installed libraries need by the docker binary at runtime is not enough since ubuntu 16.04 changed a lot the dependencies and the solution we used does not work anymore.
We get issues like the following https://github.com/docker/docker/issues/19230, for missing
dependencies. Specifically there was a missing dependency for libsystemd.so.0 on current image version (14.04) which is only available on ubuntu 15.04 > due to migration from upstart to systemd. This forces an update to the latest LTS for the image used. 
The problem occurs because i was using the latest docker binary on a 16.04 LTS host
while the image has 14.04 LTS. We cannot make assumption about the binary on host.
Btw libsystemd.so.0 was not the only one missing.

Solution:
Use 16.04 LTS as the latest base image.
Pre-install docker-in-docker (dind) in our image. Thus no host sharing of the docker binary will be needed. 
Dind used by docker [1] uses alpine linux which does not fit our purposes, fortunately the old project is still working in ubuntu so we will use it [2],[3],[4].

1. https://github.com/docker-library/docker/blob/83b2eab8bdb5d35bf343313154ab55938fca3807/1.10/dind/Dockerfile
2. https://github.com/jpetazzo/dind
3. https://hub.docker.com/r/osrg/dind-ubuntu-vivid/~/dockerfile/
4. https://hub.docker.com/r/osrg/dind-ubuntu-vivid/

In the course of this PR i bumped into this one (unfortunately it seems mesos still depends on systemd): 
https://issues.apache.org/jira/browse/MESOS-3793
A possible fix for that: --no-systemd_enable_support
Will need testing with OS X. Also test on different ubuntu versions on host.

WIP. Will have a pr shortly.

### PR DESCRIPTION
**Pull request by skonto**
fixes #77 
- updates docker image to ubuntu 16.04 LTS
- installs docker in docker image
- updates documentation we do support zookeeper and marathon

Needs testing on OS X. Tested with different ubuntu host versions.

### CODE REVIEW

**Comment by skonto** [comment]
https://issues.apache.org/jira/browse/MESOS-5244

**Comment by skonto** [comment]
An alternative here, using dcos locally: https://dcos.io/docs/1.7/administration/installing/local/

**Comment by deanwampler** [comment]
I'm trying to follow the instructions on Ubuntu 16.04 and I get stuck on these lines in `util/host_setup_ubuntu.sh`:
```
  echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | \
  sudo tee /etc/apt/sources.list.d/mesosphere.list
  sudo apt-get -y update
  sudo apt-get -y install mesos
```
It works until the last command, where it reports 
```
E: Unable to locate package mesos
```
Ideas?

**Comment by skonto** [comment]
Mesosphere has no release yet for 16.04.
http://stackoverflow.com/questions/37015871/not-able-to-install-mesos-on-ubuntu-16-04-desktop
They will be available soon.

**Comment by deanwampler** [comment]
Okay, if you make the following modification to `util/host_setup_ubuntu.sh`, it works better:
After line 55 `  CODENAME=$(lsb_release -cs)`, add:

```
if [ "$CODENAME" = 'xenial' -o  "$CODENAME" = 'trusty' ]
then
  echo "The Ubuntu '$CODENAME' release doesn't yet have a Mesos repo. Using 'trusty'."
  CODENAME=trusty
fi
```

**Comment by skonto** [comment]
yes but its really temporary. And better use vivid because there was a change in systemd from 15.04 on and calls like `sudo service start mesos-master` seem not to work with trusty isntallation. I am in the process of updating the docs and the code.

**Comment by skonto** [comment]
i will add your check in the pr.

**Comment by skonto** [comment]
done

**Comment by deanwampler** [comment]
When using on my Ubuntu VM, I found I had to run the scripts with sudo. Is that true for you? Also, when I did that, for some reason it did not like the `#######` comment line as the first line. I had to delete those lines.

**Comment by skonto** [comment]
In order to simplify using Docker, you can get non-sudo access to the Docker socket by adding your user to the docker group, then logging out and back in again:
$ sudo usermod -a -G docker $USER
$ exit

**Comment by skonto** [comment]
@deanwampler does it work for you?

**Comment by deanwampler** [comment]
Okay. I think I have it working on OSX. I have a few other small changes I'll merge from another branch.

**Comment by deanwampler** [comment]
Actually, I don't think I have write access. Go ahead and merge it, then let me know.

**Comment by skonto** [comment]
I added you as a collaborator;)

**Pull request merged**
