### PR TITLE
Shutting down mesos dispather after run and uber shell script to run …

### PR DESCRIPTION
**Pull request by nraychaudhuri**
- Shell script for one click run of the tests. Right now I made it to work for mac. For ubuntu I would need help. Maybe we merge this one and some else can add the ubuntu specific changes otherwise tell me what to do and I will update the PR.

- Shutting down mesos dispatcher after the cluster mode tests finishes.

### CODE REVIEW

**Comment by nraychaudhuri** [comment]
Good points @skonto 
I will update the docs but I wanted to get the script out to get some feedback.

In terms of resources I want the default to be minimum set of values that will make the tests run. Well I have 4 cores and it seems to run fine. I agree that we should think about the defaults. What you think should be good default?

**Comment by skonto** [comment]
I will try several several setups and see the behaviour about resources.

**Comment by nraychaudhuri** [comment]
Cool, can you push it here?

**Comment by skonto** [comment]
I tried it in a clean machine today, these are the steps i followed:
- checked out the project
- downloaded a spark tgz and unzip it
- executed ./run-tests.sh path_to_unzipped_folder mesos://172.17.0.1:5050

A few comments:

- i have to predict the mesos master ip like : 
./run-tests.sh   spark_home  172.17.0.1:5050  
this breaks the ip calculation concept we have in run.sh

-  it does not give you the option to point to a spark or hadoop binary (that can be passed to run.sh), so the developer can run the tests against it, only the default binary in run.sh is accessible, which btw must be upgraded to 1.5.2 , same in test-runner (can we automate this, picking from somewhere what is the latest stable release?). 

- if we want this to run automatically the script should unzip (/tmp) the spark binary downloaded under mesos-docker/run/binaries which is done anyway if you run the script with a clean machine. And it is the one loaded on mesos slaves and could be different from the argument passed to run-tests.sh, user does not know that...

I suggest two modes: one running as is without arguments (not so sure if it is useful to the developer but for consistency reasons eg. ./run-tests.sh picking up the latest stable release for spark) and one with two arguments for spark tgz and hadoop tgz (we could unzip the spark binary file ourselves to /tmp and use that location as spark home internally)
 
I will add resources needed for tests to run in a new comment... when i have the results.

**Comment by nraychaudhuri** [comment]
Well remember we can always start docker and explicitly call run.sh. I really don't want to make it too complicated. This would be the default option. Now the question is which one should be default. Here is my proposal to start with

- I will have the script figure out the mesos IP (like you suggested) but have the spark home passed as a parameter. In local mode most likely developer will have it checkout or unzipped somewhere. 

Makes sense?

**Comment by skonto** [comment]
if we dont specify the tgz files our script will download its own default version which might conflict  with the spark home provided by the user. The safest way i think is to enforce user to provide the correct tgzs. If not we have a potential compatibility problem there... and the run.sh script in general will not be useful as is, because by default it only downloads 1.5.1 right now which is loaded to the mesos slaves .

**Comment by dragos** [comment]
I tend to agree with @skonto. I also think that it's very rare that I need to run these tests on the Spark version that's default in `./run.sh`. Most of the times (every time?) I'm testing some changes, RC or PR.

Ideally, I'd like to use this as `./run-tests spark.tgz`, get a coffee and come back for results. Anything else is too little value, and I'd keep running `run.sh` separately anyway, since at least I get the chance to see the Mesos IP when it's printed :) The Hadoop binary I find less important, so that could be a future improvement.

**Comment by nraychaudhuri** [comment]
Alright. I completely missed the point that run.sh downloads it own spark. I will make the changes to just take the spark.tgz as a parameter and have it figure rest of the things out. Thanks guys!

**Comment by nraychaudhuri** [comment]
As suggested now run-tests.sh should only work with spark.tgz file and rest it will figure it out. I also updated the readme file. Since I am off from next week if anything comes up here @skonto can take it up

**Comment by skonto** [comment]
i will review it, merge it and continue anything needed here.

**Comment by skonto** [comment]
i tested it with 1.5.2, master(2.0.0) everything is ok.
eg.
{
  "action" : "CreateSubmissionResponse",
  "serverSparkVersion" : "2.0.0-SNAPSHOT",
  "submissionId" : "driver-20151220235122-0001",
  "success" : true
}

Command completed.

ClusterModeSpec:
- simple sum in fine-grained mode
- simple collect in fine-grained mode
- simple count in coarse-grained mode !!! IGNORED !!!
- spark.cores.max property should be honored in coarse grain mode
- simple count in fine-grain mode with role
- simple count in coarse-grained mode with role !!! IGNORED !!!
[success] Total time: 246 s, completed Dec 20, 2015 11:53:13 PM

I will merge it.

**Pull request merged**
