### PR TITLE
Remove fine-grained tests

### PR DESCRIPTION
**Pull request by mgummelt**
cc @skonto 

This test has begun to be flaky for me.  I'm not sure why, and I don't really care to diagnose since fine-grained is deprecated.  Do you mind if I remove this test @skonto?

### CODE REVIEW

**Comment by deanwampler** [comment]
That's okay with me. Can we decide on a time frame to remove this feature completely?

**Comment by mgummelt** [comment]
I don't think anyone, including Apache, would mind if we removed it in the next release (2.2).

**Comment by mgummelt** [comment]
@deanwampler Do you mind if I merge?

**Comment by deanwampler** [comment]
yes, fine with me.

**Comment by skonto** [comment]
Ok let me do a quick check and I will merge.

**Comment by skonto** [comment]
LGTM.

**Comment by mgummelt** [comment]
Thanks!

**Pull request merged**
